// <auto-generated />
namespace Rebound.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vertion2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vertion2));
        
        string IMigrationMetadata.Id
        {
            get { return "201910121500122_vertion2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
